### ISSUE TITLE
multi edit is bad

### ISSUE THREAD

**Issue by NotAKidOnSteam** [lilxyzw/lilToon#11]
it no work

you multi edit multiple materials, it only apply to last one selected

this is very sad times :<

**Comment by lilxyzw** [comment]
General property editing is supported for multi-editing.
This is a Unity specification, but it seems that multi-editing is not possible if the GUI is the same but the shaders are different.
Also, changing `Rendering Mode` and toggling `Outline` do not support multi-editing because they involve shader changes, but I will consider supporting them.
Currently there is a function to copy properties together in case multi-editing does not work.
![image](https://user-images.githubusercontent.com/74490257/153458900-a48305b4-88e6-4189-bb0c-bae52a41ec53.png)

**Comment by NotAKidOnSteam** [comment]
![image](https://user-images.githubusercontent.com/37721153/153727014-0be19967-db04-436f-b9be-a451d1e38fe2.jpeg)

It would be very nice if Fallback Shader and other similar properties could be multi-edited. It can be a bit annoying to manually set each, especially with the fallback settings.

**Comment by lilxyzw** [comment]
Multi-editing has been fixed in [lilToon 1.2.10](https://github.com/lilxyzw/lilToon/releases/tag/1.2.10).

**Comment by NotAKidOnSteam** [comment]
I appreciate your work!
