### ISSUE TITLE
Upper brightness limit is not properly applied on a mesh with shadow

### ISSUE THREAD

**Issue by kimphysik** [lilxyzw/lilToon#120]
I am testing two scenes with the same interior light settings, and different sun (exterior) light settings.
- The avatar is placed under the roof, where all the meshes are completely shaded from the sun. 
- The interior light is baked with light probes.
- The interior light has an warm color.
- The max brightness limit is set to 1.05

The following image shows the color of avatar.
![제목 없음](https://github.com/lilxyzw/lilToon/assets/98008694/00d68f16-72e7-4ffd-a37f-04ad617e2ed5)
The left side is the scene with a high sun intensity (1.4), and the right side is the scene with a low sun intensity (0.4)
- The liltoon material in the left side acts like an unlit shader
- The one in the right side shows a warm color from the light probe.

I think that these two materials should have the same shadow colors from the material settings. Maybe the clamping of the upper brightness limit is applied earlier than the shadow calculation?
I wonder if this is an expected behavior. Is there any workaround for this problem?

**Comment by lilxyzw** [comment]
This is expected behavior. The color of the light is limited by RGB=(1.05,1.05,1.05), so it looks whitish.

Below is an example calculation of how the brightness of the light changes as it is amplified.
RGB = (0.6, 0.4, 0.2) => (0.5, 0.4, 0.2) orange
RGB = (1.2, 0.8, 0.4) => (1.05, 0.8, 0.4) yellowish orange
RGB = (2.4, 1.6, 0.8) => (1.05, 1.05, 0.8) yellow
RGB = (4.8, 3.2, 1.6) => (1.05, 1.05, 1.05) white
