### ISSUE TITLE
Shader not rendering in SLZURP

### ISSUE THREAD

**Issue by Lightveld** [lilxyzw/lilToon#54]
[lilToonBugReport-2022-09-30_09.53.55.txt](https://github.com/lilxyzw/lilToon/files/9686388/lilToonBugReport-2022-09-30_09.53.55.txt)

Might be a little early to try, but am attempting to import a VRCHAT avatar over to Bonelab and the shader is turning pink as if its not supported, its currently running SLZ URP 12.1.6

I also get this error on import:
Shader error in 'Hidden/lilToonGem': redefinition of 'sampler_linear_clamp' at Assets/lilToon/Shader/Includes/lil_common_input.hlsl(11) (on d3d11)

Compiling Subshader: 0, Pass: SHADOW_CASTER, Vertex program with <no keywords>
Platform defines: SHADER_API_DESKTOP UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_REFLECTION_BUFFERS UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_PASS_SHADOWCASTER UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS
Disabled keywords: DOTS_INSTANCING_ON INSTANCING_ON SHADER_API_GLES30 UNITY_ASTC_NORMALMAP_ENCODING UNITY_COLORSPACE_GAMMA UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_NO_FULL_STANDARD_SHADER UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_VIRTUAL_TEXTURING _CASTING_PUNCTUAL_LIGHT_SHADOW

**Comment by lilxyzw** [comment]
Thank you for reporting the bug.
I have fixed this error in the dev branch.
You can use the fixed version by importing `https://github.com/lilxyzw/lilToon.git?path=Assets/lilToon#dev` from UPM.

**Comment by SSSlavic** [comment]
Also the outlines are not working in the game

**Comment by lilxyzw** [comment]
It works by setting RenderQueue to Transparent. The problem comes from `Depth Prepass`, which causes Opaque or Cutout materials to only render polygons that match the pre-rendered depth. Therefore, when using outlines, the outline depth must also be output, but URP does not allow multi-pass shaders. Geometry shaders are one solution to this problem, but they should not be used because they degrade performance, and it is better to change the RenderQueue. For general game development purposes, the [URP Renderer Feature](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@12.0/manual/urp-renderer-feature.html) can be used to solve this problem.
