### ISSUE TITLE
Invisible in HDRP

### ISSUE THREAD

**Issue by kimphysik** [lilxyzw/lilToon#55]
Hi, thank you for sharing the great shader :D I am trying to convert a BRP unity project to the HDRP. After a standard conversion process, the liltoon puts out the log that it was converted from BRP to HDRP. However, the following problem remains.

0. The liltoon is imported from https://github.com/lilxyzw/lilToon.git?path=Assets/lilToon#master in UPM.
1. **The opaque/cutout/transparent liltoon materials on SkinnedMeshRenderers are invisible, regardless of the rendering path (forward only, deferred only, both). The meshes are sometimes displayed at the world origin, not at the actual mesh position.**
2. The [high-load] ... liltoon materials on SkinnedMeshRenderers are **visible**.
3. The liltoon material on a cube is visible.
4. No error in the log

I wonder if my conversion process was wrong, or if there is a bug.

**Comment by lilxyzw** [comment]
This problem is caused by a bug in Unity. This bug does not seem to occur in Unity 2021.3.8f1 or earlier, so you may want to use a slightly older version.

Unity Issue Tracker: [GAMEOBJECTS DOESN'T GET RENDERED WHEN USING "UNLIT.UNLIT_USEPASS" SHADER](https://issuetracker.unity3d.com/issues/sphere-gameobject-doesnt-get-rendered-when-using-unlit-dot-unlit-usepass-shader)
Related Issue: #47

**Comment by kimphysik** [comment]
Downgrading to the unity 2021.3.8f1 solved the problem
